services:
  - type: web
    name: blogify-jitt
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fast:app
    envVars:
      - key: FLASK_APP
        value: fast.py
      - key: PYTHON_VERSION
        value: "3.10.12"
